name: Daily ML Pipeline Fetch and Train

on:
  schedule:
    - cron: '0 17 * * *'  # t√§glich um 17 Uhr UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch External Data
        run: |
          python scripts/fetch_weather_data.py

      # separate step to commit fetched data before processing to log via commit ID ...
      # what data the model has been trained on
      - name: Commit and Push Fetched and Processed Data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Auto: data update $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push

      - name: Process External Data
        run: |
          python scripts/process_weather_data.py

      - name: Train Model
        run: |
          python scripts/train_weather_model_linear_regression.py

      - name: Commit and Push Artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/ logs/ data/processed/
          git commit -m "Auto: processed data + model update $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push

